services:
  backend_user:
    build:
      context: ./backend/services/user-service
      dockerfile: Dockerfile
    container_name: app_backend_user
    env_file:
      - ./backend/config/.env
    expose:
      - "3001"
    volumes:
      - podsmath-uploads:/app/uploads
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - mysql
      - mongodb

  backend_transcription:
    build:
      context: ./backend/services/transcription-service
      dockerfile: Dockerfile
    container_name: app_backend_transcription
    env_file:
      - ./backend/config/.env
    expose:
      - "3002"
    volumes:
      - podsmath-models:/app/node_modules/nodejs-whisper/cpp/whisper.cpp/models
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - mysql
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend_user
      - backend_transcription
    restart: unless-stopped
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: app_mysql
    ports:
      - "3307:3306"
    env_file:
      - ./backend/config/.env
    volumes:
      - podsmath-mysql:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    networks:
      - app-network
    expose:
      - "3306"

  mongodb:
    image: mongo:7.0
    container_name: app_mongodb
    ports:
      - "27018:27017"
    env_file:
      - ./backend/config/.env
    volumes:
      - podsmath-mongo:/data/db
    restart: unless-stopped
    networks:
      - app-network
    expose:
      - "27017"

networks:
  app-network:
    driver: bridge

volumes:
  podsmath-uploads:
    driver: local
  podsmath-models:
    driver: local
  podsmath-mysql:
    driver: local
  podsmath-mongo:
    driver: local