-- MySQL Script generated by MySQL Workbench / Updated manually
-- Model: New Model    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema podsmath
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `podsmath` DEFAULT CHARACTER SET utf8 ;
USE `podsmath` ;

-- -----------------------------------------------------
-- Table `podsmath`.`imagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `podsmath`.`imagens` (
  `idimagens` INT(11) NOT NULL AUTO_INCREMENT,
  `caminho_imagem` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idimagens`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `podsmath`.`idiomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `podsmath`.`idiomas` (
  `ididiomas` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeIdiomas` VARCHAR(45) NOT NULL,
  `imagens_idimagens` INT(11) NOT NULL,
  PRIMARY KEY (`ididiomas`),
  INDEX `fk_idiomas_imagens1_idx` (`imagens_idimagens` ASC) VISIBLE,
  CONSTRAINT `fk_idiomas_imagens1`
    FOREIGN KEY (`imagens_idimagens`)
    REFERENCES `podsmath`.`imagens` (`idimagens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `podsmath`.`categorias` (NOVA TABELA)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `podsmath`.`categorias` (
  `idcategorias` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `imagens_idimagens` INT(11) NOT NULL,
  PRIMARY KEY (`idcategorias`),
  INDEX `fk_categorias_imagens1_idx` (`imagens_idimagens` ASC) VISIBLE,
  CONSTRAINT `fk_categorias_imagens1`
    FOREIGN KEY (`imagens_idimagens`)
    REFERENCES `podsmath`.`imagens` (`idimagens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `podsmath`.`temas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `podsmath`.`temas` (
  `idtemas` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `categorias_idcategorias` INT(11) NOT NULL,
  `imagens_idimagens` INT(11) NOT NULL,
  PRIMARY KEY (`idtemas`),
  INDEX `fk_temas_categorias1_idx` (`categorias_idcategorias` ASC) VISIBLE,
  INDEX `fk_temas_imagens1_idx` (`imagens_idimagens` ASC) VISIBLE,
  CONSTRAINT `fk_temas_categorias1`
    FOREIGN KEY (`categorias_idcategorias`)
    REFERENCES `podsmath`.`categorias` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_temas_imagens1`
    FOREIGN KEY (`imagens_idimagens`)
    REFERENCES `podsmath`.`imagens` (`idimagens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `podsmath`.`instituicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `podsmath`.`instituicoes` (
  `idinstituicoes` INT(11) NOT NULL AUTO_INCREMENT,
  `imagens_idimagens` INT(11) NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idinstituicoes`),
  INDEX `fk_instituicoes_imagens1_idx` (`imagens_idimagens` ASC) VISIBLE,
  CONSTRAINT `fk_instituicoes_imagens1`
    FOREIGN KEY (`imagens_idimagens`)
    REFERENCES `podsmath`.`imagens` (`idimagens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `podsmath`.`nivel_acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `podsmath`.`nivel_acesso` (
  `idnivel_acesso` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idnivel_acesso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `podsmath`.`paletacor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `podsmath`.`paletacor` (
  `idpaletaCor` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `ativado` BINARY(1) NOT NULL,
  PRIMARY KEY (`idpaletaCor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `podsmath`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `podsmath`.`usuarios` (
  `idusuarios` INT(11) NOT NULL AUTO_INCREMENT,
  `instituicoes_idinstituicoes` INT(11) NULL DEFAULT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `senha` VARCHAR(60) NULL DEFAULT NULL,
  `id_usuario_professor` INT(11) NULL DEFAULT NULL,
  `nivel_acesso_idnivel_acesso` INT(11) NOT NULL,
  `paletaCor_idpaletaCor` INT(11) NOT NULL,
  `audiosEscutados` INT(11) NOT NULL DEFAULT 0,
  `imagens_idimagens` INT(11) NOT NULL,
  PRIMARY KEY (`idusuarios`),
  INDEX `fk_usuarios_instituicoes1_idx` (`instituicoes_idinstituicoes` ASC) VISIBLE,
  INDEX `fk_usuarios_usuarios1_idx` (`id_usuario_professor` ASC) VISIBLE,
  INDEX `fk_usuarios_nivel_acesso1_idx` (`nivel_acesso_idnivel_acesso` ASC) VISIBLE,
  INDEX `fk_usuarios_paletaCor1_idx` (`paletaCor_idpaletaCor` ASC) VISIBLE,
  INDEX `fk_usuarios_imagens1_idx` (`imagens_idimagens` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_instituicoes1`
    FOREIGN KEY (`instituicoes_idinstituicoes`)
    REFERENCES `podsmath`.`instituicoes` (`idinstituicoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_nivel_acesso1`
    FOREIGN KEY (`nivel_acesso_idnivel_acesso`)
    REFERENCES `podsmath`.`nivel_acesso` (`idnivel_acesso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_paletaCor1`
    FOREIGN KEY (`paletaCor_idpaletaCor`)
    REFERENCES `podsmath`.`paletacor` (`idpaletaCor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_usuarios1`
    FOREIGN KEY (`id_usuario_professor`)
    REFERENCES `podsmath`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_imagens1`
    FOREIGN KEY (`imagens_idimagens`)
    REFERENCES `podsmath`.`imagens` (`idimagens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `podsmath`.`audios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `podsmath`.`audios` (
  `idaudios` INT(11) NOT NULL AUTO_INCREMENT,
  `temas_idtemas` INT(11) NOT NULL,
  `usuarios_idusuarios` INT(11) NOT NULL,
  `imagens_idimagens` INT(11) NOT NULL,
  `visualizacoes` INT(11) NULL DEFAULT 0,
  `titulo` TEXT NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `idiomas_ididiomas` INT(11) NOT NULL,
  PRIMARY KEY (`idaudios`),
  INDEX `fk_audios_temas1_idx` (`temas_idtemas` ASC) VISIBLE,
  INDEX `fk_audios_usuarios1_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  INDEX `fk_audios_imagens1_idx` (`imagens_idimagens` ASC) VISIBLE,
  INDEX `fk_audios_idiomas1_idx` (`idiomas_ididiomas` ASC) VISIBLE,
  CONSTRAINT `fk_audios_idiomas1`
    FOREIGN KEY (`idiomas_ididiomas`)
    REFERENCES `podsmath`.`idiomas` (`ididiomas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audios_imagens1`
    FOREIGN KEY (`imagens_idimagens`)
    REFERENCES `podsmath`.`imagens` (`idimagens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audios_temas1`
    FOREIGN KEY (`temas_idtemas`)
    REFERENCES `podsmath`.`temas` (`idtemas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audios_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `podsmath`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `podsmath`.`favoritos` (NOVA TABELA)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `podsmath`.`favoritos` (
  `usuarios_idusuarios` INT(11) NOT NULL,
  `audios_idaudios` INT(11) NOT NULL,
  `dataAdicionado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`usuarios_idusuarios`, `audios_idaudios`),
  INDEX `fk_favoritos_audios1_idx` (`audios_idaudios` ASC) VISIBLE,
  CONSTRAINT `fk_favoritos_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `podsmath`.`usuarios` (`idusuarios`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favoritos_audios1`
    FOREIGN KEY (`audios_idaudios`)
    REFERENCES `podsmath`.`audios` (`idaudios`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `podsmath`.`auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `podsmath`.`auditoria` (
  `idauditoria` INT(11) NOT NULL AUTO_INCREMENT,
  `usuarios_idusuarios` INT(11) NOT NULL,
  `mensagem` TEXT NULL DEFAULT NULL,
  `dataHora` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`idauditoria`),
  INDEX `fk_auditoria_usuarios1_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_auditoria_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `podsmath`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `podsmath`.`categoria_nivel_acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `podsmath`.`categoria_nivel_acesso` (
  `idcategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nomecategoria` VARCHAR(255) NOT NULL,
  `idnivel_acesso` INT(11) NOT NULL,
  PRIMARY KEY (`idcategoria`),
  INDEX `idnivel_acesso` (`idnivel_acesso` ASC) VISIBLE,
  CONSTRAINT `categoria_nivel_acesso_ibfk_1`
    FOREIGN KEY (`idnivel_acesso`)
    REFERENCES `podsmath`.`nivel_acesso` (`idnivel_acesso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `podsmath`.`config_nivel_acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `podsmath`.`config_nivel_acesso` (
  `idconfig` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeconfig` VARCHAR(255) NOT NULL,
  `idcategoria` INT(11) NOT NULL,
  PRIMARY KEY (`idconfig`),
  INDEX `idcategoria` (`idcategoria` ASC) VISIBLE,
  CONSTRAINT `config_nivel_acesso_ibfk_1`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `podsmath`.`categoria_nivel_acesso` (`idcategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `podsmath`.`historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `podsmath`.`historico` (
  `idhistorico` INT(11) NOT NULL AUTO_INCREMENT,
  `usuarios_idusuarios` INT(11) NOT NULL,
  `audios_idaudios` INT(11) NOT NULL,
  `tempo_audio` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`idhistorico`),
  INDEX `fk_historico_usuarios1_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  INDEX `fk_historico_audios1_idx` (`audios_idaudios` ASC) VISIBLE,
  CONSTRAINT `fk_historico_audios1`
    FOREIGN KEY (`audios_idaudios`)
    REFERENCES `podsmath`.`audios` (`idaudios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `podsmath`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `podsmath`.`transcricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `podsmath`.`transcricao` (
  `idTranscricao` INT(11) NOT NULL AUTO_INCREMENT,
  `textoTranscricao` TEXT NOT NULL,
  `audios_idaudios` INT(11) NOT NULL,
  `idiomas_ididiomas` INT(11) NOT NULL,
  PRIMARY KEY (`idTranscricao`),
  INDEX `fk_Transcricao_audios1_idx` (`audios_idaudios` ASC) VISIBLE,
  INDEX `fk_transcricao_idiomas1_idx` (`idiomas_ididiomas` ASC) VISIBLE,
  CONSTRAINT `fk_Transcricao_audios1`
    FOREIGN KEY (`audios_idaudios`)
    REFERENCES `podsmath`.`audios` (`idaudios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transcricao_idiomas1`
    FOREIGN KEY (`idiomas_ididiomas`)
    REFERENCES `podsmath`.`idiomas` (`ididiomas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;